import { Montserrat } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/navbar";
import Footer from "@/components/footer";
import AnimationProvider from "@/components/AnimationProvider";

// Import and configure the Montserrat font
const montserrat = Montserrat({ subsets: ["latin"], weight: ["400", "500", "600", "700"] });

export const metadata = {
  title: "Tech-bite",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <title>Tech-bite</title>
        <meta name="description" content="Generated by create next app" />
        
        {/* Add your company icon here */}
        <link rel="icon" href="/assets/tbite.png" type="image/png" />

        {/* Optionally add different sizes of the icon */}
        <link rel="icon" href="/assets/tbite.png"  type="image/png" />
        <link rel="icon" href="/assets/tbite.png" type="image/png" />
      </head>
      <body className={montserrat.className}>
        <div className="">
          <Navbar />
          <div className="">
            <AnimationProvider>
              {children}
            </AnimationProvider>
          </div>
          <Footer />
        </div>
      </body>
    </html>
  );
}
